### PR TITLE
Merge branches.

### PR DESCRIPTION
**Pull request by iTitus**

### CODE REVIEW

**Comment by iTitus** [comment]
I think we have to sync our formatting settings.

**Comment by AEnterprise** [comment]
please use the same settings for style as BCA as it's gona be migrated to it eventually

**Comment by iTitus** [comment]
Arent these the same settings?
I thought IntelliJ keeps them...

**Comment by BigXplosion** [comment]
these are the same :/ normally

**Comment by AEnterprise** [comment]
it depends on how you applied the settings, if you made them default, project specific or module specific. also depends on if this new code is in a new module in the same project or in a new project completely

**Pull request merged**
